### ISSUE TITLE
UCB1 arm_to_expectation not updated for all arms (potential bug)

### ISSUE THREAD

**Issue by harisankarh** [fmr-llc/mabwiser#10] opened 2019-12-16 08:41 UTC
When `partial_fit()` is done with UCB1, `arm_to_expectation` of only the arms having a reward are updated (because of [https://github.com/fmr-llc/mabwiser/blob/0c860253be017d1f393e18bf9d9d7e1739f93dca/mabwiser/ucb.py#L62](https://github.com/fmr-llc/mabwiser/blob/0c860253be017d1f393e18bf9d9d7e1739f93dca/mabwiser/ucb.py#L62) ). If an arm does not have a reward, its `arm_to_expectation` is not updated.

`arm_to_expectation` depends on `self.total_count` which gets updated when "any" of the arms are invoked. Thus, `arm_to_expectation` of all arms need to be updated when `self.total_count` changes.

Solution: remove the above condition (`if arm_rewards.size`).

Happy to submit a fix if this change can be made.

**Comment by erstrong** [comment] 2019-12-16 14:09
This is not a bug. In the expectation calculation for UCB1 you divide by the number of observations of the arm (see [documentation](https://fmr-llc.github.io/mabwiser/api.html#mabwiser.mab.LearningPolicy.UCB1) for the equation). For a new arm that number is zero, so we cannot divide by it and must leave the expectation as zero.

From a conceptual standpoint, you can think of it as if we don't have any data for an arm we cannot calculate an upper confidence bound on its unknown mean.

**Comment by skadio** [comment] 2019-12-16 23:58
@harisankarh thank you for bringing this to our attention! As @erstrong mentioned, hope the UCB1 formula clarifies this issue. 

Thank you again for your interest in our library!

**Comment by harisankarh** [comment] 2019-12-17 10:26
@erstrong @skadio Thanks for the response

@erstrong  This issue can arise even in cases other than "new arm or arm with no data" which you mentioned. 
Consider a bandit with arms `a`, `b` and `c`. 
First, `a` is invoked 10 times and the total reward obtained for `a` is 5. `a`'s `arm_to_expectation` is updated accordingly. 
Now we need to perform a `partial_fit()` with 20 invocations of `b` and `c` alone. As per the implementation, `arm_to_expectation` of `b` and `c` alone will be updated. `arm_to_expectation` of `a` won't be updated. This violates the formula mentioned in [documentation](https://fmr-llc.github.io/mabwiser/api.html#mabwiser.mab.LearningPolicy.UCB1). In this case, `N` has changed from 10 to 30 (i.e., 10 + 20). However, we are not updating `arm_to_expectation` of `a` although `n_a` is greated than zero (i.e., 10).

Another option for handling the divide-by-zero issue is to start the algorithm with `N = 1,  n_{i} = 1` instead of `N = 0,  n_{i} = 0`.

Don't know what is the right approach though.

**Comment by erstrong** [comment] 2019-12-17 14:20
@harisankarh Thank you for the further details. I see what you mean now, and thanks for catching it! 

In a previous version we checked the arm_to_count dictionary, which avoided this particular problem. We will push an update to fix the issue.

**Comment by skadio** [comment] 2019-12-20 11:31
Thank you both for brainstorming on this! And the current PR seems to address this issue.

**Comment by erstrong** [comment] 2019-12-20 14:07
PR #12 has been merged. Closing issue. Thanks again for reporting this @harisankarh!

**Closed by erstrong** 2019-12-20 14:07 UTC
Labels: bug
